variable "bucket_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "az" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_subnet_cidr" {}
variable "instance_name" {}
variable "subnet_id" {}
variable "security_group_ids" {}
